### ISSUE TITLE
Not defined Sub or Function

### ISSUE THREAD

**Issue by zeal0t35** [Pepitoh/VBad#34]
After generate the files, this message popups when i open the .doc

![imagen](https://user-images.githubusercontent.com/30702851/28938582-78ffae52-785c-11e7-8e32-b930cccdc5e0.png)

upload the vbas and the const.py
[const.py.txt](https://github.com/Pepitoh/VBad/files/1198296/const.py.txt)
[orignal_vba.txt](https://github.com/Pepitoh/VBad/files/1198295/orignal_vba.txt)
[original_vba_prepared.txt](https://github.com/Pepitoh/VBad/files/1198298/original_vba_prepared.txt)

Please help me.
Thanks in advice

**Comment by Pepitoh** [comment]
Hi,

Just keep your "Debugging()" function in original_vba_prepared.txt:
[original_vba_prepared (1).txt](https://github.com/Pepitoh/VBad/files/1199618/original_vba_prepared.1.txt)

You should delete references to Autoopen or Document_open() function in your prepared vba, VBAd will automaticly included good autopen function related to the document you are creating, it sometimes messes up when you try to add others autotrigger function.

Try this and let met know if it works. 

Pepitoh.

**Comment by zeal0t35** [comment]
Thanks Pepitoh,
I've deleted all references to the AutoOpen and DocumentOpen. In fact i've used the txt you uploaded.
Then generate file OK, 
![imagen](https://user-images.githubusercontent.com/30702851/28968498-392e9a26-78ee-11e7-9cd7-6827b9b61b5a.png)
but same error is rising.
![imagen](https://user-images.githubusercontent.com/30702851/28968526-5c3bd042-78ee-11e7-8ac8-d1cdaa8eff6d.png)

**Comment by Pepitoh** [comment]
hi @zeal0t35,

So there are many problems relative to your issue, I manage to, I think, fix them all : 
* First of all I think you misunderstood the markdown implemented for VBad. In your first file, you are for example trying to randomize Dim : 
` [rdm::15]Dim str As string`
Of course, it will cause a crash in your final VBA, you cannot randomize VBA native code, you can only apply rdm to variable or function name. The good way to use it will be : 
`Dim [rdm::15]str as String`
After that, you put exclusion marquers ([!!]) evrywhere in your prepared VBA which makes no sense (unless you want no obfucstion at all, in this case why are you using VBad for :grin:). Exclusion marquer should be used **inside** of a **string** you don't want to obfsucate. Example  : 
`[rdm::15]str = "Powershel[!!]"` not `[rdm::15] str = [!!]"powershll"` which will have no kind of effect. That is for the first file you sent.
* For the second file, the error is because you try to add too long continious string on a VBA document. You need to split it many line (as you did on the first file) in order to make it work. 
* Finaly, I also find out that VBad is not very Antivirus compatible :confused:, sometimes, modules are not created because they are deleted by antivirus at creation of the file, try to disable alll you antivirus and try again (it works for me). Disable also hidding module function -by setting `delete_module_name = 0`in const.py for debugginf more easily


Hope it helps, you can find a prepared_vba of your vba code that works perfectly on my laptop : 
[original_vba_prepared.txt](https://github.com/Pepitoh/VBad/files/1217524/original_vba_prepared.txt)


Pepitoh.

**Comment by zeal0t35** [comment]
Pepitoh:
Thank you very much for your reply.  Clear as the water 👍 
Saludos,
zeal0t
